class Columns:
    class General:
        FOOD_ID = 'Número do Alimento'
        DESCRIPTION = 'Descrição dos alimentos'

    class MicroAndMacronutrients:
        HUMIDITY = 'Umidade (%)'
        KCAL = 'Energia (kcal)'
        KJ = 'Energia (kJ)'
        PROTEIN = 'Proteína (g)'
        LIPID = 'Lipídeos (g)'
        CHOLESTEROL = 'Colesterol (mg)'
        CARBOHYDRATE = 'Carboidrato (g)'
        DIETARY_FIBER = 'Fibra Alimentar (g)'
        ASH = 'Cinzas (g)'
        CALCIUM = 'Cálcio (mg)'
        MAGNESIUM = 'Magnésio (mg)'
        MANGANESE = 'Manganês (mg)'
        PHOSPHORUS = 'Fósforo (mg)'
        IRON = 'Ferro (mg)'
        SODIUM = 'Sódio (mg)'
        POTASSIUM = 'Potássio (mg)'
        COPPER = 'Cobre (mg)'
        ZINC = 'Zinco (mg)'
        RETINOL = 'Retinol (μg)'
        RETINOL_EQUIVALENTS = 'RE (μg)'
        RETINOL_ACTIVITY_EQUIVALENTS = 'RAE (μg)'
        THIAMINE = 'Tiamina (mg)'
        RIBOFLAVIN = 'Riboflavina (mg)'
        PYRIDOXINE = 'Piridoxina (mg)'
        NIACIN = 'Niacina (mg)'
        VITAMIN_C = 'Vitamina C (mg)'

    class FattyAcids:
        SATURATED = 'Saturados (g)'
        MONO_UNSATURATED = 'Monoinsaturados (g)'
        POLY_UNSATURATED = 'Poliinsaturados (g)'
        LAURIC = '12:0 (g)'
        MYRISTIC = '14:0 (g)'
        PALMITIC = '16:0 (g)'
        STEARIC = '18:0 (g)'
        ARACHIDIC = '20:0 (g)'
        BEHENIC = '22:0 (g)'
        LIGNOCERIC = '24:0 (g)'
        MYRISTOLEIC = '14:1 (g)'
        PALMITOLEIC= '16:1 (g)'
        OLEIC = '18:1 (g)'
        GADOLEIC = '20:1 (g)'
        LINOLEIC = '18:2 n-6 (g)'
        ALPHA_LINOLENIC = '18:3 n-3 (g)'
        ARACHIDONIC = '20:4 (g)'
        TIMNODONIC = '20:5 (g)'
        CLUPANODONIC = '22:5 (g)'
        CERVONIC = '22:6 (g)'
        ELAIDIC = '18:1t (g)'
        LINOLELAIDIC = '18:2t (g)'

    class AminoAcids:
        TRYPTOPHAN = 'Triptofano (g)'
        THREONINE = 'Treonina (g)'
        ISOLEUCINE = 'Isoleucina (g)'
        LEUCINE = 'Leucina (g)'
        LYSINE = 'Lisina (g)'
        METHIONINE = 'Metionina (g)'
        CYSTINE = 'Cistina (g)'
        PHENYLALANINE = 'Fenilalanina (g)'
        TYROSINE = 'Tirosina (g)'
        VALINE = 'Valina (g)'
        ARGININE = 'Arginina (g)'
        HISTIDINE = 'Histidina (g)'
        ALANINE = 'Alanina (g)'
        ASPARTIC_ACID = 'Ácido Aspártico (g)'
        GLUTAMIC_ACID = 'Ácido Glutâmico (g)'
        GLYCINE = 'Glicina (g)'
        PROLINE = 'Prolina (g)'
        SERINE = 'Serina (g)'
